### ISSUE TITLE
YarpRobotLoggerDevice segsfault if YARP_ROBOT_NAME is not defined 

### ISSUE THREAD

**Issue by davidegorbani** [ami-iit/bipedal-locomotion-framework#699]
As per title, this is the trace if the variable is not defined 
```
(gdb) where
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:234
#1  0x00007f6479b4d238 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(char const*) () at /lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f647036af00 in BipedalLocomotion::YarpRobotLoggerDevice::setupTelemetry(std::weak_ptr<BipedalLocomotion::ParametersHandler::IParametersHandler const>, double const&)
    (this=0x55e7696c2820, params=std::weak_ptr<const BipedalLocomotion::ParametersHandler::IParametersHandler> (use count 2, weak count 1) = {...}, devicePeriod=@0x7ffeded6b840: 0.01)
    at /home/dgorbani/software/robotology-superbuild/src/bipedal-locomotion-framework/devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp:452
#3  0x00007f647036927e in BipedalLocomotion::YarpRobotLoggerDevice::open(yarp::os::Searchable&) (this=0x55e7696c2820, config=...)
    at /home/dgorbani/software/robotology-superbuild/src/bipedal-locomotion-framework/devices/YarpRobotLoggerDevice/src/YarpRobotLoggerDevice.cpp:342
#4  0x00007f647939f680 in yarp::dev::PolyDriver::coreOpen(yarp::os::Searchable&) () at /home/dgorbani/software/robotology-superbuild/build/install/lib/libYARP_dev.so.3
#5  0x00007f64793a063b in yarp::dev::PolyDriver::open(yarp::os::Searchable&) () at /home/dgorbani/software/robotology-superbuild/build/install/lib/libYARP_dev.so.3
#6  0x00007f6479ccade2 in yarp::robotinterface::Device::open() () at /home/dgorbani/software/robotology-superbuild/build/install/lib/libYARP_robotinterface.so.3
#7  0x00007f6479cd24a3 in yarp::robotinterface::Robot::Private::openDevices() () at /home/dgorbani/software/robotology-superbuild/build/install/lib/libYARP_robotinterface.so.3
#8  0x00007f6479cd7571 in yarp::robotinterface::Robot::enterPhase(yarp::robotinterface::ActionPhase) () at /home/dgorbani/software/robotology-superbuild/build/install/lib/libYARP_robotinterface.so.3
#9  0x000055e769163cbd in yarprobotinterface::Module::configure(yarp::os::ResourceFinder&) ()
#10 0x00007f6479901847 in yarp::os::RFModule::runModule(yarp::os::ResourceFinder&) () at /home/dgorbani/software/robotology-superbuild/build/install/lib/libYARP_os.so.3
#11 0x000055e769160dbf in main ()
```

**Comment by GiulioRomualdi** [comment]
I will open a PR as soon as possible to fix it!
